package aras; //paquete al que pertenece la clase

import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author mjgod
 */
public class Administrador extends javax.swing.JFrame {

    //public static RegistrarAlumnos1 registrarAlumnos = new RegistrarAlumnos1();
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        // metodos para poder modificar la interfaz visual por codigo
        setSize(650,430); 
        setResizable(false);
        setTitle("Sistema de Registro");
        setLocationRelativeTo(null);
        //cuando se cierra la ventana, termina de ejecutarse el programa
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        //establece la imagen como fondo de la aplicacion
        ImageIcon wallpaper = new ImageIcon("src/images/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        
    }
    
    //Reemplazar el icono de java por default
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/cuatroVientos.jpg"));
        return retValue;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_RegistrarAlumnos = new javax.swing.JButton();
        jButton_GestionarAlumnos = new javax.swing.JButton();
        jButton_ListarAlumnos = new javax.swing.JButton();
        jLabel_RegistrarAlumnos = new javax.swing.JLabel();
        jLabel_ListarAlumnos = new javax.swing.JLabel();
        jLabel_GestionarAlumnos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Registro de Alumnos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jButton_RegistrarAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png"))); // NOI18N
        jButton_RegistrarAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_RegistrarAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_RegistrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, 100));

        jButton_GestionarAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.png"))); // NOI18N
        jButton_GestionarAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_GestionarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 120, 100));

        jButton_ListarAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/listar.png"))); // NOI18N
        jButton_ListarAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_ListarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ListarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 120, 100));

        jLabel_RegistrarAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RegistrarAlumnos.setText("Registrar Alumnos");
        getContentPane().add(jLabel_RegistrarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel_ListarAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ListarAlumnos.setText("Listar Alumnos");
        getContentPane().add(jLabel_ListarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jLabel_GestionarAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_GestionarAlumnos.setText("Gestionar Alumnos");
        getContentPane().add(jLabel_GestionarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 383, 40, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarAlumnosActionPerformed
        // TODO add your handling code here:
        RegistrarAlumnos1 registrarAlumnos = new RegistrarAlumnos1();
        registrarAlumnos.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarAlumnosActionPerformed

    private void jButton_GestionarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarAlumnosActionPerformed
        
        GestionarAlumnos gestionarAlumnos = new GestionarAlumnos();
        gestionarAlumnos.setVisible(true);
        
    }//GEN-LAST:event_jButton_GestionarAlumnosActionPerformed

    private void jButton_ListarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarAlumnosActionPerformed
        // TODO add your handling code here:
        ListarAlumnos listarAlumnos = new ListarAlumnos();
        listarAlumnos.setVisible(true);
    }//GEN-LAST:event_jButton_ListarAlumnosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ayuda ayuda = new Ayuda();
        ayuda.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_GestionarAlumnos;
    private javax.swing.JButton jButton_ListarAlumnos;
    private javax.swing.JButton jButton_RegistrarAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_GestionarAlumnos;
    private javax.swing.JLabel jLabel_ListarAlumnos;
    private javax.swing.JLabel jLabel_RegistrarAlumnos;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
