package aras;

import static aras.InformaciónAlumnos3.fechaActual;
import clases.Conexion;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPage;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author mjgod
 */
public class RegistrarAlumnos3 extends javax.swing.JFrame {
    public static int cont = 0;
    
    /**
     * Creates new form RegistrarAlumnos1
     */
    public RegistrarAlumnos3() {
        initComponents();
        
        setResizable(false);
        setTitle("Sistema de Registro");
        setSize(700,500);
        setLocationRelativeTo(null);
        //cuando se cierra la ventana, termina de ejecutarse el programa
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        //establece la imagen como fondo de la aplicacion
        ImageIcon wallpaper = new ImageIcon("src/images/fondo.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }
    
    //Reemplazar el icono de java por default
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/cuatroVientos.jpg"));
        return retValue;
    }
    
    public static String fechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_alergias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cobertura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_condicion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_inscripcion = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton_cuota = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox_sangre = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_retira_con = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_observaciones = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Información Médica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alergias:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txt_alergias.setBackground(new java.awt.Color(51, 102, 255));
        txt_alergias.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_alergias.setForeground(new java.awt.Color(255, 255, 255));
        txt_alergias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_alergias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cobertura médica:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txt_cobertura.setBackground(new java.awt.Color(51, 102, 255));
        txt_cobertura.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_cobertura.setForeground(new java.awt.Color(255, 255, 255));
        txt_cobertura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cobertura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Padece de alguna condición médica:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txt_condicion.setBackground(new java.awt.Color(51, 102, 255));
        txt_condicion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_condicion.setForeground(new java.awt.Color(255, 255, 255));
        txt_condicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_condicion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_condicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Paga Inscripción:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Grupo sanguíneo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        buttonGroup1.add(jRadioButton_inscripcion);
        jRadioButton_inscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_inscripcion.setText("SI");
        getContentPane().add(jRadioButton_inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("NO");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Paga Cuota:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        buttonGroup2.add(jRadioButton_cuota);
        jRadioButton_cuota.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_cuota.setText("SI");
        getContentPane().add(jRadioButton_cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("NO");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jComboBox_sangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-", "0+", "A-", "A+", "B-", "B+", "AB" }));
        getContentPane().add(jComboBox_sangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Observaciones:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        txt_retira_con.setBackground(new java.awt.Color(51, 102, 255));
        txt_retira_con.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_retira_con.setForeground(new java.awt.Color(255, 255, 255));
        txt_retira_con.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_retira_con.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_retira_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 210, 25));

        jTextArea_observaciones.setColumns(20);
        jTextArea_observaciones.setRows(5);
        jScrollPane1.setViewportView(jTextArea_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 210, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Se retira con:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< Anterior");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 50));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Finalizar >");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 140, 50));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //RegistrarAlumnos2 registrarAlumnos2 = new RegistrarAlumnos2();
        RegistrarAlumnos4.registrarAlumnos2.setVisible(true);
        RegistrarAlumnos2.registrarAlumnos3.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String nombre, apellido, lugar, fecha, localidad, domicilio, nombre_madre, nombre_padre, telefono, telefono2, nombre_escuela, grado, genero, repitio, grado_repetido, alergias, cobertura, condicion, sangre, retira_con, observaciones, inscripcion, cuota;
        int dni, dni_madre, dni_padre, numero_escuela;
        
        nombre = RegistrarAlumnos1.nombre;
        apellido = RegistrarAlumnos1.apellido;
        nombre_madre = RegistrarAlumnos1.nombre_madre;
        nombre_padre = RegistrarAlumnos1.nombre_padre;
        lugar = RegistrarAlumnos1.lugar;
        fecha = RegistrarAlumnos1.fecha;
        localidad = RegistrarAlumnos1.localidad;
        domicilio = RegistrarAlumnos1.domicilio;
        telefono = RegistrarAlumnos1.telefono;
        telefono2 = RegistrarAlumnos1.telefono2;
        dni = Integer.parseInt(RegistrarAlumnos1.dni);
        dni_madre = Integer.parseInt(RegistrarAlumnos1.dni_madre);
        dni_padre = Integer.parseInt(RegistrarAlumnos1.dni_padre);
        
        nombre_escuela = RegistrarAlumnos2.nombre_escuela;
        numero_escuela = Integer.parseInt(RegistrarAlumnos2.numero_escuela);
        genero = RegistrarAlumnos2.genero;
        grado = RegistrarAlumnos2.grado;
        repitio = RegistrarAlumnos2.repitio;
        grado_repetido = RegistrarAlumnos2.grado_repetido;
        
        alergias = txt_alergias.getText().trim();
        cobertura = txt_cobertura.getText().trim();
        condicion = txt_condicion.getText().trim();
        retira_con = txt_retira_con.getText().trim();
        observaciones = jTextArea_observaciones.getText();
        //sangre = jComboBox_sangre.getSelectedIndex() + 1;
        sangre = jComboBox_sangre.getSelectedItem().toString();
        
        if(jRadioButton_inscripcion.isSelected()){
            inscripcion = "SI";
        } else {
            inscripcion = "NO";
        }
        
        if(jRadioButton_cuota.isSelected()){
            cuota = "SI";
        } else {
            cuota = "NO";
        }
        
        if(observaciones.equals("")){
            observaciones = "s/o";
        }
        
        
        try {
            Connection cn2 = Conexion.conectar();
            PreparedStatement pst2 = cn2.prepareStatement("insert into alumnos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            pst2.setInt(1, cont);
            pst2.setString(2, nombre);
            pst2.setString(3, apellido);
            pst2.setInt(4, dni);
            pst2.setString(5, fecha);
            pst2.setString(6, lugar);
            pst2.setString(7, domicilio);
            pst2.setString(8, localidad);
            pst2.setString(9, nombre_madre);
            pst2.setInt(10, dni_madre);
            pst2.setString(11, nombre_padre);
            pst2.setInt(12, dni_padre);
            pst2.setString(13, telefono);
            pst2.setString(14, telefono2);
            pst2.setInt(15, numero_escuela);
            pst2.setString(16, nombre_escuela);
            pst2.setString(17, grado);
            pst2.setString(18, repitio);
            pst2.setString(19, grado_repetido);
            pst2.setString(20, sangre);
            pst2.setString(21, alergias);
            pst2.setString(22, cobertura);
            pst2.setString(23, condicion);
            pst2.setString(24, retira_con);
            pst2.setString(25, observaciones);
            pst2.setString(26, inscripcion);
            pst2.setString(27, cuota);
            pst2.setString(28, fechaActual());
            pst2.setString(29, genero);
                        
            pst2.executeUpdate();
            cn2.close();
            this.dispose();
                        
            } catch (SQLException e) {
                System.err.println("Error en Registrar usuario. " + e);
                JOptionPane.showMessageDialog(null, "¡ERROR al registrar alumno!, contacte al administrador.");
    }//GEN-LAST:event_jButton2ActionPerformed
    
        RegistrarAlumnos1.registrarAlumnos4.subirFamiliares();
        
        
        int input = JOptionPane.showConfirmDialog(null, "¿Quiere imprimir la ficha de inscripción?");
        // 0=yes, 1=no, 2=cancel
        System.out.println(input);
        
        if(input == 0) {
            Document documento = new Document(); //creo objeto de la clase document
            try {
                String ruta = System.getProperty("user.home"); //ruta donde se guarda el archivo
                PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Ficha" + apellido + nombre + ".pdf")); //complementamos la ruta

                com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/BannerFicha.jpg"); //agrego el header
                header.scaleToFit(300, 900); //tamaño del header
                header.setAlignment(Chunk.ALIGN_CENTER); //posicion centrada del header

                Paragraph parrafo = new Paragraph(); //creo el parrafo del pdf
                parrafo.setAlignment(Paragraph.ALIGN_CENTER);
                //parrafo.add("Ficha de Inscripción\n\n");
                parrafo.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY)); //le doy la fuente
                Font font = new Font(FontFactory.getFont(FontFactory.TIMES_ROMAN,13.0f,Font.BOLD,BaseColor.BLACK));

                documento.open();
                documento.add(header); //le agrego los elementos al documento
                documento.add(parrafo);

                documento.add(new Paragraph("Fecha de inscripción: " + fechaActual() + "\n",font));
                documento.add(new Paragraph("Nombre: " + nombre + "                Apellido: " + apellido + "\n",font));
                //documento.add(new Paragraph("Apellido: " + apellido));
                documento.add(new Paragraph("DNI: " + dni + "\n",font));
                documento.add(new Paragraph("Lugar de nacimiento: " + lugar + "                Fecha de nacimiento: " + fecha + "\n",font));
                //documento.add(new Paragraph("Fecha de nacimiento: " + fecha));
                documento.add(new Paragraph("Domicilio: " + domicilio + "                Localidad: " + localidad + "\n",font));
                //documento.add(new Paragraph("Localidad: " + localidad));
                documento.add(new Paragraph("Nombre de la Madre: " + nombre_madre + "                DNI: " + dni_madre + "\n",font));
                //documento.add(new Paragraph("DNI: " + dni_madre));
                documento.add(new Paragraph("Nombre del Padre: " + nombre_padre + "                DNI: " + dni_padre + "\n",font));
                //documento.add(new Paragraph("DNI: " + dni_padre));
                documento.add(new Paragraph("Teléfono de contacto: " + telefono + "\n",font));
                documento.add(new Paragraph("Otro teléfono de contacto: " + telefono2 + "\n\n",font));

                documento.add(new Paragraph("Grupo familiar del alumno:\n\n",font));
                PdfPTable tabla = new PdfPTable(4); //agrego las columnas
                
                // Set Table Total Width
                tabla.setWidthPercentage(100);
                tabla.setTotalWidth(1000);

                // Set Each Column Width - Make Sure Array is the same number specified in constructor
                tabla.setWidths(new int[]{350, 275, 100, 275});

                tabla.addCell(new Paragraph("NOMBRE Y APELLIDO",font));
                tabla.addCell(new Paragraph("PARENTESCO",font));
                tabla.addCell(new Paragraph("EDAD",font));
                tabla.addCell(new Paragraph("OCUPACIÓN",font));

                try {
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement("select nombre_familiar, parentesco, edad, ocupacion from familiares where dni_familiar = '" + dni +"'");

                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {
                        do {                        

                            tabla.addCell(new Paragraph(rs.getString(1),font));
                            tabla.addCell(new Paragraph(rs.getString(2),font));
                            tabla.addCell(new Paragraph(rs.getString(3),font));
                            tabla.addCell(new Paragraph(rs.getString(4),font));

                        } while (rs.next());
                        documento.add(tabla);
                    }

                } catch (SQLException e) {
                    System.out.println("Error al generar lista de alumnos. " + e);
                }

                documento.add(new Paragraph("\nNombre de Escuela: " + nombre_escuela + "                Número: " + numero_escuela + "\n",font));
                //documento.add(new Paragraph("Número: " + numero_escuela));
                documento.add(new Paragraph("Grado/Curso: " + grado + "                Repitió grado alguna vez: " + repitio + "                ¿Qué Grado? " + grado_repetido + "\n",font));
                //documento.add(new Paragraph("Repitió grado alguna vez: " + repitio));
                //documento.add(new Paragraph("¿Qué Grado repitió? " + grado_repetido));

                documento.add(new Paragraph("Grupo sanguíneo: " + sangre + "               Alergias: " + alergias + "                Cobertura médica: " + cobertura + "\n",font));
                //documento.add(new Paragraph("Alergias: " + alergias));
                //documento.add(new Paragraph("Cobertura médica: " + cobertura));
                documento.add(new Paragraph("Padece de alguna condición médica: " + condicion + "\n",font));
                documento.add(new Paragraph("Se retira acompañado de: " + retira_con + "\n",font));
                documento.add(new Paragraph("Observaciones: " + observaciones + "\n",font));
                documento.add(new Paragraph("Paga Inscripción: " + inscripcion + "                Paga Cuota: " + cuota + "\n\n",font));
                //documento.add(new Paragraph("Paga Cuota: " + cuota));


                Paragraph parrafo2 = new Paragraph(); //creo el parrafo del pdf
                parrafo2.setAlignment(Paragraph.ALIGN_CENTER);
                parrafo2.add("__________________________________________________________\n");
                documento.add(parrafo2);
                
                Font f=new Font(FontFactory.getFont(FontFactory.TIMES_ROMAN,12.0f,Font.BOLDITALIC,BaseColor.BLACK));
                
                Paragraph terminos = new Paragraph("Por la presente, autorizo a mi hijo que concurra y participe en todas las actividades"
                        + " en el Centro Educativo Cuatro Vientos. Dejo constancia que estoy de acuerdo con los términos "
                        + "y condiciones de la inscripción del alumno.\n", f);
                //terminos.setFont(FontFactory.getFont("Tahoma", 12, Font.BOLD, BaseColor.GREEN));
                documento.add(terminos);

                documento.add(new Paragraph("Firma Madre, Padre o Tutor:\n",f));
                documento.add(new Paragraph("Aclaración y Parentesco:\n",f));
                documento.add(new Paragraph("DNI:\n",f));
                
                

                documento.close();
                JOptionPane.showMessageDialog(null, "Ficha de alumno creada correctamente.");



            } catch (Exception e) {
                System.out.println("Error al generar PDF. " + e);
            }
        }
        
        System.exit(0); //Para cerrar toda la aplicación
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlumnos3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlumnos3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlumnos3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAlumnos3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAlumnos3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_sangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton_cuota;
    private javax.swing.JRadioButton jRadioButton_inscripcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_observaciones;
    private javax.swing.JTextField txt_alergias;
    private javax.swing.JTextField txt_cobertura;
    private javax.swing.JTextField txt_condicion;
    private javax.swing.JTextField txt_retira_con;
    // End of variables declaration//GEN-END:variables
}
